# -*- coding: utf-8 -*-
"""Copy_of_Bio_Gas_Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/rka0285058-afk/Artificial-Intelligence/blob/main/Copy_of_Bio_Gas_Simulation.ipynb
"""

from google.colab import drive
drive.mount('/content/drive')

print("DataFrame Info:")
df.info()

import pandas as pd

file_path = '/content/drive/MyDrive/Software/biogas_dataset.csv'
df = pd.read_csv(file_path)

print(f"Successfully loaded '{file_path}' into a DataFrame.")
display(df.head())

print("\nDescriptive Statistics:")
display(df.describe())

print("\nMissing values per column:")
missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]
if not missing_values.empty:
    display(missing_values)
    print("\nHandling missing values: For simplicity, we will drop rows with any missing values. For a more robust approach, imputation strategies could be explored.")
    df_cleaned = df.dropna()
    print(f"Original rows: {len(df)}, Rows after dropping missing values: {len(df_cleaned)}")
else:
    print("No missing values found.")
    df_cleaned = df.copy()

from sklearn.model_selection import train_test_split

# Define the target variable
target_column = 'biogas_production'
y = df_cleaned[target_column]

# Define features (all columns except the target and potentially ID/time-based columns if not used as features)
# For this dataset, 'Year', 'Month', 'Day' can be kept as numerical features or engineered further if needed.
X = df_cleaned.drop(columns=[target_column])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Features (X) shape: {X.shape}")
print(f"Target (y) shape: {y.shape}")
print(f"Training features (X_train) shape: {X_train.shape}")
print(f"Testing features (X_test) shape: {X_test.shape}")

from sklearn.ensemble import RandomForestRegressor

# Initialize and train a RandomForestRegressor model
# RandomForest is chosen for its robustness and good performance on various datasets
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1) # n_jobs=-1 uses all available processors
model.fit(X_train, y_train)

print("RandomForestRegressor model trained successfully.")

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Model Performance on Test Set:")
print(f"Mean Absolute Error (MAE): {mae:.3f}")
print(f"Mean Squared Error (MSE): {mse:.3f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.3f}")
print(f"R-squared (R2): {r2:.3f}")

# Optional: Display feature importances (useful for understanding the model)
print("\nFeature Importances:")
feature_importances = pd.Series(model.feature_importances_, index=X_train.columns).sort_values(ascending=False)
display(feature_importances.head(10)) # Display top 10 most important features

import pandas as pd

file_path = '/content/drive/MyDrive/Software/biogas_dataset.csv'
df = pd.read_csv(file_path)

print(f"Successfully loaded '{file_path}' into a DataFrame.")
display(df.head())

"""The data preprocessing steps are complete, and there were no missing values found in your dataset. I've successfully trained a RandomForestRegressor model to predict biogas production. The model performed well on the test set:

Mean Absolute Error (MAE): 2.605
Mean Squared Error (MSE): 11.027
Root Mean Squared Error (RMSE): 3.321
R-squared (R2): 0.911
An R-squared value of 0.911 indicates that approximately 91.1% of the variance in biogas production can be explained by the features in your dataset, which is a strong result.

I've also identified the top 10 most important features for predicting biogas production:

Pig Manure (kg): 48.9%
Kitchen Food Waste (kg): 15.8%
Cassava (kg): 11.5%
Municipal Residue (kg): 6.3%
Chicken Litter (kg): 5.8%
Bagasse Feed (kg): 3.8%
Water (L): 1.2%
Temperature (C): 1.2%
Energy Grass (kg): 0.7%
Fish Waste (kg): 0.6%
It appears that 'Pig Manure (kg)', 'Kitchen Food Waste (kg)', and 'Cassava (kg)' are the most influential factors. What would you like to do next? Would you like to visualize the predictions, try optimizing the model, or explore the data further?

I have successfully loaded your biogas production dataset, performed initial data checks (including descriptive statistics and missing value assessment), split the data into training and testing sets, and trained a RandomForestRegressor model. The model achieved a strong R-squared value of 0.911, indicating good predictive performance, and I've also highlighted the most important features influencing biogas production.

If you have any further questions or would like to explore other aspects of the data or model, please let me know!

All previous requests have been completed. I have successfully loaded your data, performed exploratory data analysis, trained a Random Forest Regressor model to predict biogas production, and evaluated its performance. The model achieved an R-squared value of 0.911, and I've highlighted the most influential features. If you have any further questions or new tasks, please let me know!

All previously requested tasks have been completed. I have successfully loaded your biogas_dataset.csv file, performed initial data inspections and cleaned the data (no missing values were found). Subsequently, I trained a RandomForestRegressor model to predict biogas production, which achieved a strong R-squared score of 0.911 on the test set. I also identified the most influential features for biogas production, with 'Pig Manure (kg)', 'Kitchen Food Waste (kg)', and 'Cassava (kg)' being the most significant. I am now awaiting your next instruction.

All previously requested tasks have been completed. I have successfully loaded your biogas_dataset.csv file, performed initial data inspections and cleaned the data (no missing values were found). Subsequently, I trained a RandomForestRegressor model to predict biogas production, which achieved a strong R-squared score of 0.911 on the test set. I also identified the most influential features for biogas production, with 'Pig Manure (kg)', 'Kitchen Food Waste (kg)', and 'Cassava (kg)' being the most significant. I am now awaiting your next instruction.

All previously requested tasks have been completed. I have successfully loaded your biogas_dataset.csv file, performed initial data inspections and cleaned the data (no missing values were found). Subsequently, I trained a RandomForestRegressor model to predict biogas production, which achieved a strong R-squared score of 0.911 on the test set. I also identified the most influential features for biogas production, with 'Pig Manure (kg)', 'Kitchen Food Waste (kg)', and 'Cassava (kg)' being the most significant. I am now awaiting your next instruction.


"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # 45-degree line
plt.xlabel('Actual Biogas Production')
plt.ylabel('Predicted Biogas Production')
plt.title('Actual vs. Predicted Biogas Production')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()